### model
model_name_or_path: /models/huggingface/Qwen/Qwen3-14B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_target: all
deepspeed: /app/examples/deepspeed/ds_z2_config.json

### dataset
dataset: alpaca_en_demo
dataset_dir: /app/data
template: qwen3
cutoff_len: 32768
max_samples: 1000000000
overwrite_cache: true
preprocessing_num_workers: 16
enable_thinking: false

### output
output_dir: saves/qwen3-32b/lora/sft
logging_steps: 2
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard 

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

sequence_parallel_size: 4
# sequence_parallel_mode: zigzag-ring
sequence_parallel_mode: ulysses

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 2
